spring:
  datasource:
    url: jdbc:postgresql://77.232.130.183:5432/organizillamain
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8084
  servlet:
    context-path: /api