spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**
        - id: stub-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/stub/**
          filters:
            - CustomGatewayFilter


server:
  port: 8082
custom-properties:
  jwt:
    secret: jsonwebtokensecretphrasepneumonoultramicroscopicsilicovolcanoconiosisantidisestablishmentarianism
    issuer: ilya