spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**
        - id: account
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/account/**
          filters:
            - CustomGatewayFilter
        - id: board-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/workspace/**
          filters:
            - CustomGatewayFilter
server:
  port: 8082
custom-properties:
  jwt:
    secret: jsonwebtokensecretphrasepneumonoultramicroscopicsilicovolcanoconiosisantidisestablishmentarianism
    issuer: ilya